package io.izzel.freshwaterfish.server;

import io.izzel.freshwaterfish.boot.application.Main_Forge;

import java.io.*;

public class Launcher {

    private static final int MIN_CLASS_VERSION = 61;
    private static final int MIN_JAVA_VERSION = 17;
    private static final String EULA_URL = "https://account.mojang.com/documents/minecraft_eula";
    private static final String EULA_FILE = "eula.txt";

    public static void main(String[] args) throws Throwable {
        int javaVersion = (int) Float.parseFloat(System.getProperty("java.class.version"));
        if (javaVersion < MIN_CLASS_VERSION) {
            System.err.println("Arclight requires Java " + MIN_JAVA_VERSION);
            System.err.println("Current: " + System.getProperty("java.version"));
            System.exit(-1);
            return;
        }

        if (!checkEula()) {
            System.err.println("You need to agree to the EULA to run the server.");
            System.exit(-1);
            return;
        }

        // Check and create server.properties if not exists
        checkServerProperties();

        Main_Forge.main(args);
    }

    private static void checkServerProperties() throws IOException {
        File serverProperties = new File("server.properties");
        if (!serverProperties.exists()) {
            System.out.println("Creating default server.properties file...");
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(serverProperties))) {
                writer.write("#Minecraft server properties\n");
                writer.write("#Generated by FreshwaterFish server\n");
                writer.write("spawn-protection=16\n");
                writer.write("max-tick-time=60000\n");
                writer.write("query.port=25565\n");
                writer.write("server-name=FreshwaterFish Server\n");
                writer.write("generator-settings=\n");
                writer.write("enable-command-block=false\n");
                writer.write("force-gamemode=false\n");
                writer.write("game-mode=survival\n");
                writer.write("enable-query=false\n");
                writer.write("player-idle-timeout=0\n");
                writer.write("difficulty=easy\n");
                writer.write("spawn-monsters=true\n");
                writer.write("broadcast-console-to-ops=true\n");
                writer.write("op-permission-level=4\n");
                writer.write("pvp=true\n");
                writer.write("entity-broadcast-range-percentage=100\n");
                writer.write("snooper-enabled=true\n");
                writer.write("level-type=default\n");
                writer.write("hardcore=false\n");
                writer.write("enable-status=true\n");
                writer.write("enable-whitelist=false\n");
                writer.write("max-players=20\n");
                writer.write("network-compression-threshold=256\n");
                writer.write("resource-pack-sha1=\n");
                writer.write("max-world-size=29999984\n");
                writer.write("function-permission-level=2\n");
                writer.write("rcon.port=25575\n");
                writer.write("server-port=25565\n");
                writer.write("server-ip=\n");
                writer.write("spawn-npcs=true\n");
                writer.write("allow-flight=false\n");
                writer.write("level-name=world\n");
                writer.write("view-distance=10\n");
                writer.write("resource-pack=\n");
                writer.write("spawn-animals=true\n");
                writer.write("white-list=false\n");
                writer.write("rcon.password=\n");
                writer.write("generate-structures=true\n");
                writer.write("max-build-height=256\n");
                writer.write("online-mode=true\n");
                writer.write("level-seed=\n");
                writer.write("use-native-transport=true\n");
                writer.write("prevent-proxy-connections=false\n");
                writer.write("enable-rcon=false\n");
                writer.write("motd=A FreshwaterFish Minecraft Server\n");
            }
            System.out.println("Default server.properties file created successfully.");
        }
        
        // Create plugins directory if it doesn't exist
        File pluginsDir = new File("plugins");
        if (!pluginsDir.exists()) {
            System.out.println("Creating plugins directory...");
            if (pluginsDir.mkdirs()) {
                System.out.println("Plugins directory created successfully.");
            } else {
                System.err.println("Failed to create plugins directory.");
            }
        }
    }

    private static boolean checkEula() throws IOException {
        File eulaFile = new File(EULA_FILE);

        if (eulaFile.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(eulaFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    if (line.trim().startsWith("eula=")) {
                        String value = line.trim().substring(5); // Get content after "eula="
                        if (value.trim().equalsIgnoreCase("true")) {
                            return true; // EULA already accepted
                        } else {
                            // Explicitly set to false, or some other value, require re-acceptance
                            System.out.println("EULA is currently set to \"" + value.trim() + "\", but needs to be accepted to run the server.");
                            return promptUserForEula(eulaFile, true); // true indicates we're updating existing file
                        }
                    }
                }
            }
        }

        return promptUserForEula(eulaFile, false);
    }

    private static boolean promptUserForEula(File eulaFile, boolean isUpdating) throws IOException {
        System.out.println("By running this server, you agree to the Minecraft EULA.");
        System.out.println("Read the EULA at: " + EULA_URL);
        System.out.print("Do you agree to the EULA? (y/N): ");

        // Don't use try-with-resources here to avoid closing System.in
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        try {
            String input = reader.readLine();
            if (input != null && input.trim().toLowerCase().startsWith("y")) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter(eulaFile))) {
                    writer.write("# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).\n");
                    writer.write("# Generated via FreshwaterFish server\n");
                    writer.write("eula=true\n");
                }
                System.out.println("EULA has been " + (isUpdating ? "updated" : "accepted") + " and saved.");
                return true;
            } else {
                System.out.println("EULA not accepted. Server will not start.");
                return false;
            }
        } finally {
            // Don't close the reader to avoid closing System.in
        }
    }
}
